### PR TITLE
Moved hot key handling and clipboard impl to crossterm.

### LINKED ISSUE #94: Pushing Ctrl + C after running `sendme send example_file.c` results in terminal output breaking
- After the successful completion of previous issues (like #69), `sendme` is now nearly 100% functional and fully usable on both GNU/Linux and Android (Termux). On GNU/Linux both the stable release (currently 0.26.0) and the development branch can work, getting the stable branch using `cargo install sendme`, but on Termux, currently the development branch is necessary to resolve an error, using `cargo install --git https://github.com/n0-computer/sendme` to install `sendme`.

I was testing the program a little bit, and I ran into a small problem with the sending functionality of the program,

when using `sendme send file.c`, then pushing Ctrl + C after receiving the file on a different device, unfortunately, the terminal will get messed up in a way that makes stdout not work. 

<details>
<summary>(large image hidden for readability - click to show)</summary>

Image

</details>

so, you can still type commands, as shown, but you can't see what you type
restarting the terminal emulator or SSH connection makes the temporary problem disappear.
the problem is reproducible on Termux and on GNU/Linux and also with both the development and  stable branches of the program.

When I test on multiple computers, I am able to reproduce this effect on both x86_64 and aarch64, on both GNU/Linux and Termux, and with both the development branch from github and the stable release from `cargo install sendme`.

Here are the brief specs of two computers where I reproduced this problem. On the GNU/Linux computer, the problem was reproduced using both the stable branch and the development branch, but on the Android device, the problem was reproduced using only the branch that works there at this time, the github development branch.

- up to date Gentoo GNU/Linux with Kitty terminal, Xorg X11 server, and Rust 1.87.0, on an x86_64 computer

- LineageOS 20 Android 13 running Termux 0.119.0-beta.1 with up-to-date packages and Rust 1.88.0, on an aarch64 Samsung Galaxy A70 SM-A705FN phone.
  - **Android platform notes**, just in case, for reference by anyone who has not used `sendme` with Termux, but has previously used `sendme` with another operating system: 
    - Slightly older versions of Termux App and very old versions of Android are usually supported for an extended period of time because they are sometimes less convenient for users to update than Termux internal packages,
    - and as long as Termux's updateable internal packages are all up-to-date, older versions of Android are expected to work properly in most situations, and bugs reproducible on them are usually (but not always) reproducible on all Android versions.
    - Android versions 7.0 and newer are expected to mostly work with Termux
    - Termux App versions 0.118.0 and newer are supported, but upgrading to the newest Termux app is preferred.
    - Termux internal packages should always be kept up to date regularly using `pkg upgrade`,
    - and new upgrades of internal packages are supposed to be, and usually are, backwards compatible with Termux 0.118.0 and Android 7.0
    - This information is current to July 2025 and will eventually change in the future, because sometimes Termux discontinues support for receiving new package updates on old Termux Apps and very old Android versions.

- May be in some way internally related to other, previously-reported Ctrl+C-related bugs:
  - https://github.com/n0-computer/sendme/issues/78
  - https://github.com/n0-computer/sendme/issues/47

I think it can be hoped that maybe, with some luck, if one or both of the preexisting Ctrl+C related issues were fixed, it's possible that the improved Ctrl+C handler might automatically prevent this third problem from happening as well. Unfortunately, I haven't read a lot of the `sendme` code yet, and I'm not sure if there's an easy way to fix this or not yet.

### PR DESCRIPTION
**Pull request by Jisu-Woniu**
Closes #94.

However, this brings more dependencies and is expected to longer compilation time.

The buggy `read_key` impl in `console` will keep the terminal in raw mode, where subsequent commands in shell won't see echo.

What's more, Ctrl+C used by tokio is tricky on Windows, so I am not aware how to trigger that correctly in new clipboard handling block.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -743,21 +744,49 @@ async fn send(args: SendArgs) -> anyhow::Result<()> {
...
+                        code: KeyCode::Char('c'),
+                        modifiers: KeyModifiers::CONTROL,
+                        kind: KeyEventKind::Press,
+                        ..
+                    })) => {
+                        disable_raw_mode()
+                            .unwrap_or_else(|e| eprintln!("Failed to disable raw mode: {e}\r"));
+                        kill(Pid::from_raw(0), Some(Signal::SIGINT))
+                            .unwrap_or_else(|e| eprintln!("Failed to end process: {e}"));
+                    }
```
Comment (Jisu-Woniu) [inline src/main.rs]: This is where Windows build would fail since I tried to trigger a UNIX signal using UNIX `kill` syscall.

**Comment by Jisu-Woniu** [comment]
I need someone with Windows device to test whether Ctrl+C will quit the default compiled program, thanks!

You need to:

- Install the version compiled from [my fork](https://github.com/Jisu-Woniu/sendme)
  ```shell
  # On a windows device: (need --force if sendme is already in .cargo/bin)
  cargo install --git https://github.com/Jisu-Woniu/sendme.git
  ```
- Run `sendme send <SOME-RANDOM-FILE>`
- **After** the program says `press c to copy command to clipboard ...`, press Ctrl+C.
- Ensure the program exit correctly, and the terminal behaves correctly when running `echo Hello` or something like that.
- If anything went wrong during that, notice me

File: src/main.rs (hunk 1 above)
Comment (Jisu-Woniu) [reply src/main.rs]: Now it will compile, but I wonder whether it works correctly on Windows.

**Comment by Jisu-Woniu** [comment]
Having tested it on my friend's Windows 10 PC with Windows Terminal. The above process works as expected.

**Review by robertkirkman — APPROVED** [review]
I have tested building and running this PR for Termux (Android) and I can confirm that it also prevents the problem of terminal output breaking after pushing Ctrl + C to stop sending on Termux.

**Comment by rklaehn** [comment]
So how do I reproduce this with the original sendme? Run it on windows and then hit control-c? Ah, never mind. It is in the issue.

**Comment by Jisu-Woniu** [comment]
Windows may or may not be affected by the original issue, I just want to check if the PR works on Windows. Never mind, I have tested it on my friend's Windows 10 PC.

File: src/main.rs (hunk 1 above)
Comment (dignifiedquire) [reply src/main.rs]: why do you need to trigger `kill` can't you simply exit the process?

Comment (Jisu-Woniu) [reply src/main.rs]: `kill` means "send signal to process". We will send (actually, resend since Ctrl+C is not handled automatically in raw mode) a `SIGINT` to the process itself so it will run the cleanup process correctly (like deleting temp files).

Comment (Jisu-Woniu) [reply src/main.rs]: This matches the original `read_key` behavior in `console` crate:

https://docs.rs/console/latest/src/console/unix_term.rs.html#351-362

```rust
    // if the user hit ^C we want to signal SIGINT to ourselves.
    if let Err(ref err) = rv {
        if err.kind() == io::ErrorKind::Interrupted {
            if !ctrlc_key {
                unsafe {
                    libc::raise(libc::SIGINT);
                }
            } else {
                return Ok(Key::CtrlC);
            }
        }
    }
```

Comment (dignifiedquire) [reply src/main.rs]: I see, unfortunate, but does make sense

File: src/main.rs [hunk 2]
```diff
@@ -743,21 +744,69 @@ async fn send(args: SendArgs) -> anyhow::Result<()> {
...
         let _keyboard = tokio::task::spawn(async move {
-            let term = Term::stdout();
             println!("press c to copy command to clipboard, or use the --clipboard argument");
-            loop {
-                if let Ok(Key::Char('c')) = term.read_key() {
-                    add_to_clipboard(&ticket);
-                }
-            }
+
+            // `enable_raw_mode` will remember the current terminal mode
```
Comment (dignifiedquire) [inline src/main.rs]: this is becoming very long, can you put this into a function please?

**Review by dignifiedquire — APPROVED** [review]
thanks
